# Generated by Django 4.2.7 on 2025-11-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Уникальное название меню для использования в template tag",
                        max_length=100,
                        unique=True,
                        verbose_name="Название меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название пункта"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Может быть явным URL (например: /page/) или named URL (например: page1)",
                        max_length=200,
                        verbose_name="URL",
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="Имя URL из urls.py (например: page1). Используется если URL не задан явно.",
                        max_length=200,
                        verbose_name="Named URL",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menu",
                        verbose_name="Меню",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.menuitem",
                        verbose_name="Родительский пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["order", "title"],
                "indexes": [
                    models.Index(
                        fields=["menu", "parent"], name="menu_menuit_menu_id_3f0bd7_idx"
                    )
                ],
            },
        ),
    ]
